### ISSUE TITLE
[1.20.1] Request: Make Automation Easier For The Big Dissolution Chamber

### ISSUE THREAD

**Issue by Shugabush** [Y-Xiao233/IndustrialForegoingExtraUpgrades#82]
Can you make it so that the max number of items allowed in a given slot is equal to how many operations can run at once? That would make automation so much easier. Right now I have to have a complex Integrated Dynamics setup for it to work properly. I do have bigger stacks mod installed, so I don't want to use the stack limit to mitigate this issue.

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/1be8bdfb-d10a-4aab-8a74-7c1dfef98261" />

**Comment by Shugabush** [comment]
> Perhaps we can add a slot input quantity limit.When the thread is 12,each slot can only input 12 items.How about this?

Update: This issue is still present in the latest version. Below is what my pattern provider inserted into the chamber when making liquid dragon breath. The dragon breath bottles all go into one slot, even if I have no thread addon installed.

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/9a3f89cc-ddb2-427e-a8d1-5525e70aecf5" />

**Comment by Y-Xiao233** [comment]
The latest version has been fixed, you need to modify the configuration file to enable it(config/ifeu/machine.toml)

Change this value from 0 to 1
<img width="2300" height="540" alt="Image" src="https://github.com/user-attachments/assets/06dac3f0-5c65-4339-9334-1a7ae8ae2ec4" />

**Comment by Shugabush** [comment]
It still doesn't work. I've assigned the input rule to 1.

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/f93c4f09-1e3f-4c76-b72e-8a704a0deeec" />

**Comment by Shugabush** [comment]
I still have one issue. If I have more than 8 of an item in an external inventory trying to insert into the big dissolution chamber, it doesn't send. I have to manually split it up into two or more parts less than 8. Can you please make it so that having 16 items (for example) can automatically split 8 items each into 2 slots?

https://github.com/user-attachments/assets/e63985be-e0a1-42b4-87ae-5482cc2ca2c6
